services:
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8080:8080"
    networks:
      - microservices-new-feignclient_default

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8085:8085"
    networks:
      - microservices-new-feignclient_default
    depends_on:
      - inventory-service

  shipping-service:
    build: ./shipping-service
    container_name: shipping-service
    ports:
      - "8090:8090"
    networks:
      - microservices-new-feignclient_default

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8091:8091"
    networks:
      - microservices-new-feignclient_default

networks:
  microservices-new-feignclient_default:
    external: true