spring:
  application:
    name: shipping-service
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/shipping_system
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    schema-registry-url: http://localhost:8081

    # Consumer configuration
    consumer:
      group-id: shipping-service-group
      auto-offset-reset: earliest

    # Streams configuration
    streams:
      application-id: ${spring.application.name}-streams
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        processing.guarantee: exactly_once_v2
        commit.interval.ms: 1000
        cache.max.bytes.buffering: 0

# Application specific configuration
app:
  kafka:
    topics:
      order-submitted: order-submitted
      shipment-created: shipment-created

# Logging configuration
logging:
  level:
    com.shippingmanagement: INFO
    org.apache.kafka: WARN
    org.apache.kafka.streams: INFO
server:
  port: 8090