spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shipping_system
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

server:
  port: 8085

app:
  inventory-service-url: http://localhost:8080
  kafka:
    topics:
      order-submitted: order-submitted
      order-inventory-retry: order-inventory-retry
      order-inventory-dlt: order-inventory-dlt
